server:
  port: 8081
  shutdown: graceful
  tomcat:
    connection-timeout: 60s
    uri-encoding: UTF-8
    threads:
      max: 1000
      min-spare: 30

---
spring:
  profiles:
    active: dev

  application:
    name: backend

  main:
    allow-circular-references: true

  jackson:
    date-format: yyy-MM-dd HH:mm:ss
    time-zone: GMT+8
---
spring:
  datasource:
    url: jdbc:p6spy:mysql://localhost:3306/global_db_test?useSSL=false&sslMode=DISABLED
    username: root
    password: vshow
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    type: com.zaxxer.hikari.HikariDataSource

    hikari:
      minimum-idle: 5
      maximum-pool-size: 15
      keepalive-time: 50000
      idle-timeout: 45000
      max-lifetime: 540000


mybatis-plus:
  check-config-location: true
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      #全局默认主键类型
      id-type: auto
      logic-delete-value: 1
      logic-not-delete-value: 0
      logic-delete-field: delete_at
  #mapper xml映射路径
  mapper-locations: classpath*:mapper/**/*Mapper.xml



knife4j:
  enable: true

#开启和暴露端点
management:
  endpoint:
    health:
      probes:
        enabled: true
      show-details: ALWAYS
  endpoints:
    web:
      exposure:
        include: '*'
  health:
    readinessstate:
      enabled: true
    livenessstate:
      enabled: true
